"""Edited some fields in feature usage

Revision ID: 098b76a21fd5
Revises: ec7041ded076
Create Date: 2025-09-30 01:34:26.204865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '098b76a21fd5'
down_revision: Union[str, Sequence[str], None] = 'ec7041ded076'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feature_usages', sa.Column('used_count', sa.Integer(), nullable=False))
    op.add_column('feature_usages', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('feature_usages', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('feature_usages', sa.Column('max_limit', sa.Integer(), nullable=False))
    op.drop_column('feature_usages', 'count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feature_usages', sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('feature_usages', 'max_limit')
    op.drop_column('feature_usages', 'updated_at')
    op.drop_column('feature_usages', 'created_at')
    op.drop_column('feature_usages', 'used_count')
    # ### end Alembic commands ###
