"""Edited feature usage

Revision ID: 60a60e8476e4
Revises: 098b76a21fd5
Create Date: 2025-09-30 15:03:46.889409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60a60e8476e4'
down_revision: Union[str, Sequence[str], None] = '098b76a21fd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feature_usages', 'max_limit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feature_usages', sa.Column('max_limit', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
