"""Edited some fields in user_plan

Revision ID: ec7041ded076
Revises: 447c5b9c6744
Create Date: 2025-09-30 00:04:02.657076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec7041ded076'
down_revision: Union[str, Sequence[str], None] = '447c5b9c6744'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_plans_plan_expires_at'), 'user_plans', ['plan_expires_at'], unique=False)
    op.create_unique_constraint(None, 'user_plans', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_plans', type_='unique')
    op.drop_index(op.f('ix_user_plans_plan_expires_at'), table_name='user_plans')
    # ### end Alembic commands ###
